### real drone
rgb_image: "/d400/color/image_raw"
depth_image: "/d400/aligned_depth_to_color/image_raw"
#camera_info: "/d400/depth/camera_info"
camera_info: "/d400/aligned_depth_to_color/camera_info"
depth_optical_frame: "d400_depth_optical_frame"
#depth_optical_frame: "d400_aligned_depth_to_color_frame"
depth_scale_factor: 0.001 #real camera

### simulation gazebo
#rgb_image: "/depth_camera/depth_camera/image_raw"
#depth_image: "/depth_camera/depth/disparity"
#camera_info: "/depth_camera/depth_camera/camera_info"
#depth_optical_frame: "camera_depth_optical_frame"
#depth_scale_factor: 1.0 #sim

inspection_dist: 1.0   

kp_x: 0.3
kd_x: 0.0
ki_x: 0.0

kp_y: 0.15
kd_y: 0.0
ki_y: 0.0

kp_z: 0.15
kd_z: 0.0
ki_z: 0.0
